# Generated by Django 4.2.9 on 2026-06-16 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialty')),
            ],
        ),
    ]
