# Generated by Django 4.2.9 on 2026-06-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicalkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients_treated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
