# Generated by Django 4.2.9 on 2026-06-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_doctor_patients_treated_doctor_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(default='Main Clinic', max_length=255),
        ),
    ]
